:output:
  Instructor:
    :options:
      :fields:
        - id
        - user_id
        - first_name
        - last_name
        - username
        - locations
        - preferred_locations
        - sport
        - status
        - overall_initial_rank
        - kids_initial_rank
        - adults_initial_rank
  User:
    :options:
        :fields:
        - id
        - email
        - user_type
        - location_id

  Lesson:
    :options:
      :fields:
        - id
        - instructor_id
        - requester
        - ability_level
        - deposit_status
        - lesson_time_id
        - activity
        - location
        - state
        - duration
        - start_time
